save_dir: '/home/shiqi_w/code/field-circuit-param-periodic-koopman/results/Plain/experiment_5_same'
data_dir: '/home/shiqi_w/code/field-circuit-param-periodic-koopman/data/Mur1000Js1.2'
step_size: 20
sample_step: 1
pca_dim: 6
inputs_dim: 2
params_dim: 2
batch_size: 256
validation_split: 0.2
dictionary_dim: 45
dictionary_layers: [64, 128, 6]
u_dictionary_dim: 20
u_layers: [64, 64, 6]
A_layers: [1, 1, 1]
B_layers: [1, 1, 1]
lr: 0.001
step_size_lr: 400
gamma_lr: 0.9
epochs: 5000
encoder_type: 'Transformer_like'
Description: '为了防止过拟合，我减少了operater network的自由度（六层降低为3层），并且我将pca_dim由4改成了6'
