save_dir: '/home/shiqi/code/Project2-sensor-case/field-circuit-param-periodic-koopman/results/Similar/experiment_1_same'
data_dir: '/home/shiqi/code/Project2-sensor-case/field-circuit-param-periodic-koopman/data/Mur1000Js1.2'
step_size: 10
sample_step: 1
pca_dim: 4
inputs_dim: 2
params_dim: 2
batch_size: 256
validation_split: 0.2
dictionary_dim: 45
dictionary_layers: [2, 2, 2]
A_layers: [2, 2, 2]
B_layers: [2, 2, 2]
lr: 0.001
step_size_lr: 200
gamma_lr: 0.9
epochs: 5000
