save_dir: '/home/shiqi_w/code/field-circuit-param-periodic-koopman/results/Orthogonal/experiment_3_same'
data_dir: '/home/shiqi_w/code/field-circuit-param-periodic-koopman/data/Mur1000Js1.2'
step_size: 10
sample_step: 1
pca_dim: 7
inputs_dim: 2
params_dim: 2
batch_size: 512
validation_split: 0.2
dictionary_dim: 45
dictionary_layers: [64, 128, 6]
u_dictionary_dim: 20
u_layers: [64, 64, 6]
Q_layers: [1, 1, 1]
T_layers: [1, 1, 1]
B_layers: [1, 1, 1]
lr: 0.001
step_size_lr: 400
gamma_lr: 0.9
epochs: 5000
encoder_type: 'Transformer_like'
Description: 'This is the same as experiment_1_same, but with a different dictionary. The dictionary is the same with previous work, with a transformer-like encoder. Also, a input encoder is consrtructed.'
